# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetterboxdTui < Formula
  desc "Local-first Letterboxd TUI with diary sync, stats, and heatmaps"
  homepage "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap/releases/download/v0.1.2/letterboxd-tui_darwin_amd64.tar.gz"
      sha256 "f5fdf22ca499dbacd5d35c6f41eca01f99af3a2f392d7b5ea70ae55d4d6deae2"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap/releases/download/v0.1.2/letterboxd-tui_darwin_arm64.tar.gz"
      sha256 "e7ae4f6acf059898c30fc55627d7018d652c380a0bf4060b3c8ac67475fb06c5"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap/releases/download/v0.1.2/letterboxd-tui_linux_amd64.tar.gz"
      sha256 "e3f8298182869d8c6b8de7639d4c30dd0fad5101108c3cb81ebe1f40d0c64411"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap/releases/download/v0.1.2/letterboxd-tui_linux_arm64.tar.gz"
      sha256 "f3c90aee64dba5184f533dbd7867c9d533cd86cc2c299f97e26fe39385086369"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  test do
    system "#{bin}/letterboxd-tui", "help"
  end
end
