# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetterboxdTui < Formula
  desc "Local-first Letterboxd TUI with diary sync, stats, and heatmaps"
  homepage "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_amd64.tar.gz"
      sha256 "ed12faaf9e760c613958aeea378c4bb60995f312ae2eb43f493b6732a3c40bfd"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_arm64.tar.gz"
      sha256 "f9440b14247aa86a106a1679edaea3c3ca710ea68e8c0df0cc9f4fa4c5c56527"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_amd64.tar.gz"
      sha256 "58beac5f1ed69dfa501f52bf4807cc8478538323f5c70b8e65839dadae89a1f0"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_arm64.tar.gz"
      sha256 "2e5efc57871918dc8dca6cf0d924e1c64cf5fd435b556a641eb076f8911dafb1"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  test do
    system "#{bin}/letterboxd-tui", "help"
  end
end
