# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetterboxdTui < Formula
  desc "Local-first Letterboxd TUI with diary sync, stats, and heatmaps"
  homepage "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_amd64.tar.gz"
      sha256 "14345565550ba2cf0c8a30d7a5cd6e488780bb1732c5a8cd351d57e918b707f1"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_arm64.tar.gz"
      sha256 "9cc74a7db9c146a6de9c95491a0b3a0f7ac61b88836f1b26d6a14f1901c2eeb0"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_amd64.tar.gz"
      sha256 "df3bbb7d869d61ade15bc5cb334cd44dafd9c5b72610c19aac83fa295dd04cb1"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_arm64.tar.gz"
      sha256 "5186c59f664a7b4834580f1356219d4637219407846ede456fd981276749a77c"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  test do
    system "#{bin}/letterboxd-tui", "help"
  end
end
