# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetterboxdTui < Formula
  desc "Local-first Letterboxd TUI with diary sync, stats, and heatmaps"
  homepage "https://github.com/moKshagna-p/letterboxd-TUI-Heatmap"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_amd64.tar.gz"
      sha256 "2dae1c38e28211ad76023fca7882da152a11b7792a30666664d139390689f54b"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_darwin_arm64.tar.gz"
      sha256 "2a1c57fd6e6be5381f40c5cadd401875408af48d40cc2fa7b54b99660815a54a"

      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_amd64.tar.gz"
      sha256 "85fde20171179f1ec0053cac381dad87639cc04e80efc967d7a9dc7de9298c57"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moKshagna-p/letterboxd-CLI/releases/download/v0.1.4/letterboxd-tui_linux_arm64.tar.gz"
      sha256 "74ff52bf5b1169d0676f660928532126eab748d41f7566102cd0fecb5e5ff640"
      define_method(:install) do
        bin.install "letterboxd-tui"
      end
    end
  end

  test do
    system "#{bin}/letterboxd-tui", "help"
  end
end
